apiVersion: v1
kind: Secret
metadata:
    name: kopia-secret
type: Opaque
stringData:
    KOPIA_PASSWORD: ENC[AES256_GCM,data:j5viMvzTTVFNMw==,iv:/McmwaHupZcFMMSJ4p/kH8VXS6postf64m8R6inF9xQ=,tag:/1ap2Led2BAwqaCalulKOQ==,type:str]
sops:
    age:
        - recipient: age1en4cf0wprkkt486yz5v68ee2duqsfj2w064x27dk0mnnxse8gs7q47fznp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTDNISk41Q0ptbEJaWkgr
            b3BOZXk4bDJYa3ZLV2pWSU8wREVwejBVTW5NCkRvTzl6VVE2VWl4V3RHZ213a2x4
            RWFKdkczeFNoY2tFL1hXZUFDbXcyNU0KLS0tIEZkQnRDMEQwR1NybjNYRU1NcXVY
            T3hJZ3c0ZnZtaGdybmorL2VBRFVZWXcKZOKgw5r+ySxcCy8HXS+OieU65gExEqt4
            peDC//wGVAfbv0h0feIqAx2n0MynKTopO5nsS1k2aPy+iyrSJ2lCjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T21:42:33Z"
    mac: ENC[AES256_GCM,data:dCNIX2O7JhUgp0tdj0je+FAQjOxQh0nYahHcQdtaZisoHwANSIQH5QTuGCBD/30xUsPpc3Zrzb/fIL5fpTtWQmEs19BV6ZotjxY2pStri6KCw+T+xXPIkg0QBynOkS5yoMrBQsy8qruRNBstEaRWIM0G9z6AnzuGSHTEaGa7hAY=,iv:YPp4g0Qww0V3XqyP95IBNm+YWhbaaP7+kSTBUXM/qT0=,tag:Bx2DzF5iMlegA4kkgYBfTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
